### ISSUE TITLE
Alignment issue in URL bar

### ISSUE THREAD

**Issue by glazed0** [dannycandle/FluidFox#3]
I've noticed an alignment issue in the URL bar on MacOS 12.2.1
Firefox version 110.0b9 (64-bit) Developer Edition
![fy7b444gj7-BB](https://user-images.githubusercontent.com/70531810/218524367-635911ac-2467-46d0-930c-538f12cce754.jpg)
![4mt8tu456e-BB](https://user-images.githubusercontent.com/70531810/218524375-e43c5e2e-cddb-4384-aaf8-94fb623122e1.jpg)

**Comment by kucho** [comment]
Hey @glazed0, you can fix it adding this to your `userChrome.css`:

```css
 #urlbar-input-container {
   display: flex;
   align-items: center;
 }

 .urlbar-input-box {
   width: 100%;
 }

```
